### ISSUE TITLE
API to interact with

### ISSUE THREAD

**Issue by CheweyZ** [schneidmaster/gitreports.com#113]
so we can just send say a post event to you in eg a JSON string and then the issue could be opened rather than load up your site

reason is the project im working on needs to be incredibly lightweight that we can't even afford the space of the captcha image we have managed to keep our project size down so it's 90KB and the reports sites is 74KB which in comparison is massive

Thanks

**Comment by schneidmaster** [comment]
I don't think this is within the scope of the project. Git Reports is basically just a web interface for the [GitHub API](https://developer.github.com/v3/issues/), you should just use that API directly to create your issues.
