### ISSUE TITLE
Provide API for autosubmission from apps (with repo-specific key) and dedup

### ISSUE THREAD

**Issue by Sophist-UK** [schneidmaster/gitreports.com#126]
Allow apps to automatically submit error reports.

Will need some sort of key to replace CAPTCHA, and functionality to avoid duplicated issues.

**Comment by schneidmaster** [comment]
I think this is definitely outside the scope of Git Reports. Users should just use the github API directly to automatically create issues; I don't think Git Reports can add anything by proxying a stripped-down version.

**Comment by Sophist-UK** [comment]
Fair enough.
