### ISSUE TITLE
Issue Details field needs to be taller or auto-expand to fit text

### ISSUE THREAD

**Issue by Sophist-UK** [schneidmaster/gitreports.com#129]
When I prefill the Issue Details field with multiple lines of text from the Get Params, they are not all shown.

**Comment by ccd0** [comment]
The field is indeed much too small and is encouraging people to write few or no details. Just setting the height to 400px or so and removing the `no-resize` CSS class would go a long way.

**Comment by ZeWaka** [comment]
This issue could also be solved by just making it expandable by the user with the removal of the `no-resize` css, as said above. This would greatly improve the service.

**Comment by ccd0** [comment]
Thanks! Much appreciated.
