### ISSUE TITLE
404 on your report an issue

### ISSUE THREAD

**Issue by bwoodsend** [schneidmaster/gitreports.com#193]
Hi,

You have an ironic broken link on your home page. https://gitreports.com/

Where is says at the bottom:

>  Dogfood it with a bug report [here](https://gitreports.com/issue/schneidmaster/gitreports.com),

The link on `here` gives 404.

**Comment by schneidmaster** [comment]
Thanks! I actually intentionally temporarily disabled the repo -- I started getting a bunch of spam submissions (which seem to be real people and are getting past the CAPTCHA). This is just a side project I built a few years back so I don't have a ton of time to invest going to war with the spammers; I'll probably try adding Akamai or something when I find the time.

**Comment by bwoodsend** [comment]
Ahh, that's unfortunate. I saw [this](https://bitbucket.org/fschwebel/django-misery/src/master/) for shaking off spam users a wee while ago. You probably can't use is unless you just happen to be using django but it would be satisfying and/or entertaining if you could.
