### ISSUE TITLE
Issue created from Git report

### ISSUE THREAD

**Issue by maimoona-bashir** [schneidmaster/gitreports.com#200]
![Issue](https://user-images.githubusercontent.com/63979852/86272136-5179b380-bb8b-11ea-83de-b1d7e2711000.PNG)
maimoona-bashir is authors name, but the issue is submitted by someone else. when a issue is submitted it shows 
" #issue opened by Author (rather than the person who created the issue)"

**Comment by schneidmaster** [comment]
This is working correctly; the issues are submitted to GitHub using the account of the person who set up Git Reports. If you would like issues to be ascribed directly to your users then they would need their own GitHub accounts anyway so you don't need Git Reports.

**Comment by maimoona-bashir** [comment]
The report was created by the user with their own GitHub account, it still shows "opened by 'Author-Name'"

**Comment by schneidmaster** [comment]
I don't understand -- users don't use a GitHub account when submitting issues, the issue form is open to the public (which is the point of the service). If your users already have GitHub accounts then you don't need Git Reports, they can just directly open issues on your repo.

**Comment by maimoona-bashir** [comment]
I'm sorry, if it's not making sense. I tried to logout from Git account and
tried creating an issue from Git reports form but it still shows the same
"Opened by author's name".


Regards,
Maimoona Bashir

**Comment by schneidmaster** [comment]
That is the correct behaviour. All issues will be submitted to GitHub using the account of the person who configured Git Reports.

**Comment by maimoona-bashir** [comment]
[image: image.png]

If you have a look at the picture above,  the first 4 issues are created by
Maimoona Bashir via Git Report form, it was configured by Jace Riehl an
year ago. but it was not working due to change in the repository, so I
fixed it today (as I was working on it). Although it's working now but if
you see the issue #603 and #602 they are showing accurate behaviour e.g
"opened by 'the person who created it "  opened by strinsberg  , opened by
johnanvik respectively, i want this behaviour  with the issue created via
Git report form.
Regards,
Maimoona Bashir

**Comment by schneidmaster** [comment]
The screenshot didn't come through the email. Regardless, I am not sure how else to explain. Git Reports attributes issues to the user who configured it. It doesn't know or care if the end user submitting an issue has a GitHub account.

**Comment by maimoona-bashir** [comment]
screenshot attached. please check.
Regards,
Maimoona Bashir

**Comment by schneidmaster** [comment]
You have to log into GitHub in your browser to attach the screenshot. GitHub doesn't include attachments in comments from email replies.

**Comment by maimoona-bashir** [comment]
Does it mean that when a user (who has or doesn't have a GitHub account)
whenever create an issue from the Git Report form, the issue will be made
from the "JaceRiehl" name?
Regards,
Maimoona Bashir

**Comment by schneidmaster** [comment]
Correct.

**Comment by maimoona-bashir** [comment]
I have attached a screenshot on your gitHub Repository. you can delete it
after having a look at it.

Regards,
Maimoona Bashir

**Comment by maimoona-bashir** [comment]
please check the screenshot , is this the correct behaviour?

Regards,
Maimoona Bashir

**Comment by schneidmaster** [comment]
Yes, that is correct.

**Comment by maimoona-bashir** [comment]
Thank you for your response, it helped.
Regards,
Maimoona Bashir
