### ISSUE TITLE
Issue submitted by Git report 

### ISSUE THREAD

**Issue by maimoona-bashir** [schneidmaster/gitreports.com#201]
![Issue](https://user-images.githubusercontent.com/63979852/86274624-3446e400-bb8f-11ea-99e2-2397b7a809b3.PNG)

maimoona-bashir is authors name, but the issue is submitted by someone else. when a issue is submitted it shows
" #issue opened by Author (rather than the person who created/submitted the issue)"

**Comment by schneidmaster** [comment]
Duplicate of #200.

**Comment by maimoona-bashir** [comment]
I have tried doing it from 2 different user accounts But it still shows the author’s name.
