### ISSUE TITLE
Is it supposed to take this long?

### ISSUE THREAD

**Issue by TheDarkMuffin** [schneidmaster/gitreports.com#67]
Each time I've tried making use of Git Reports, I'd make a new repo named test or something and then it wouldn't show. I'd wait an hour and then it'd say "Refreshing repository information from GitHub..." above my previous repos (some of which I've deleted), and then it stays like that for hours. I take a nap, wake up and my new repos are there.

I just wanted to report this. If it's supposed to happen, I can live with it, but if not, can it be fixed?

**Comment by schneidmaster** [comment]
Git Reports refreshes from GitHub whenever you log out and log in (I should probably add the ability to trigger a refresh manually). So next time, create your repository, then on Git Reports hover over your name on the right side of the nav and click Logout, and then log back in.

>  and then it stays like that for hours

Repositories are loaded by a side job in Sidekiq. Occasionally it will hang (I haven't been able to reproduce a consistent issue and figure out why) and that will happen. Again, logging out and back in will solve.

**Comment by TheDarkMuffin** [comment]
Oh, okay. Thanks! This worked!
