### ISSUE TITLE
CAPTCHA is broken

### ISSUE THREAD

**Issue by jimcavoli** [schneidmaster/gitreports.com#68]
Noticed specifically on https://gitreports.com/issue/OA-C4/C4App

Observed functionality:

* CAPTCHA image is not found, visiting the image's URL gives a 500 error
* The text box has 'translation missing' written in it
* Anything entered into the text box fails with a message that the CAPTCHA was incorrect (sort of expected that though)

**Comment by schneidmaster** [comment]
Issue fixed. It appeared to be an issue with the server running out of memory and then Imagemagick couldn't allocate enough memory to generate the CAPTCHA images. I will look into the issue further to determine why the memory leak is happening.
