### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by schneidmaster** [schneidmaster/gitreports.com#7]
Add an optional CAPTCHA to the report page, so developers can avoid getting spammed with Issues.

**Comment by TheDarkMuffin** [comment]
I see a CAPTCHA that says "captcha" and then "translation missing" below it. And nothing I can think to type seems to work.

**Comment by TheDarkMuffin** [comment]
http://stackoverflow.com/questions/20313384/translation-missing-in-simple-captcha Seems to be a common issue.

**Comment by jimcavoli** [comment]
Issue opened for failing CAPTCHA; see #68
