### ISSUE TITLE
Profile stuck in "Refreshing repository information from GitHub..."

### ISSUE THREAD

**Issue by Maxwolf** [schneidmaster/gitreports.com#70]
I setup my account to allow players to submit bug reports to an indie games private repo to make our lives easy and not have multiple repos.

Worked perfectly when I first set it up and got the first few tickets in, I went to check on it today and could not send myself test bugs to either repo.

My profile on the site says it is perpetually refreshing the list of repos from Github. I revoked the access of the application and let it re-configure it thinking that might help but now I cannot see any repos.

I fear I just made things worse now, wondering if there is anything that can be done on your end.

**Comment by schneidmaster** [comment]
Looking into this, will report back tonight.

**Comment by Maxwolf** [comment]
Thank you!

**Comment by schneidmaster** [comment]
Apologies for the delay - I'm a college senior and life approaching graduation is crazy. Essentially, there are sporadic issues involving the Sidekiq jobs that handle refreshing repositories and submitting issues. I believe the issue was related to Sidekiq consuming all the server memory, and adding a memory cap to the Sidekiq config seems to have solved the issue (or at least it hasn't recurred in the 10+ days since I did that).

**Comment by Maxwolf** [comment]
No worries! Busy here also, thanks for taking a look into things. I got the bugs and emails that got caught up in the system was only a few thankfully :)

I would say you can mark this as fixed for now since everything is in order!

**Comment by sebastianskejoe** [comment]
Seems this is a problem again. I got an issue through four days ago, but today no issues come through and the profile page is stuck on "Refreshing repository ...".

**Comment by schneidmaster** [comment]
It appears to have to do with how Sidekiq workers are being started. I can see your request enqueued but for some reason it is not being removed from the queue and executed even though none of the workers are busy. I will investigate.

**Comment by sebastianskejoe** [comment]
Just recieved the issues that got stuck and successfully tested the formular again - thank you very much for resolving this so quick and for providing a great service! :+1:
