### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by ad-m** [schneidmaster/gitreports.com#79]
Is there any translations support for UI? I want to do full translation form into Polish, but I can't find any *.po or *.mo files.

**Comment by schneidmaster** [comment]
I have added support for translations for public-facing pages using i18n. For a Polish translation, please duplicate [config/locals/en.yml](https://github.com/schneidmaster/gitreports.com/blob/master/config/locales/en.yml) to `config/locals/pl.yml`, translate the text, and submit a PR.

**Comment by ad-m** [comment]
Translation still doesn't work.
```
$ curl 'https://gitreports.com/issue/ad-m/poradnia.siecobywatelska.pl' -H 'Accept-Language: pl,pl_PL,pl-pl' 2>/dev/null | grep 'CAPTCHA'
            <p>Please complete the following CAPTCHA to prove that you&#39;re a human.</p>
```

**Comment by schneidmaster** [comment]
Ah, I had to add more code to check the request header. Should work now.

**Comment by ad-m** [comment]
Thanks you very much. Everything work perfect in my browser:

![zaznaczenie_335](https://cloud.githubusercontent.com/assets/3618479/8639546/65f2dee0-28dd-11e5-9424-322eb060a1a3.png)
