### ISSUE TITLE
Git cloning (v2.6.4 windows) is not working on windows 10

### ISSUE THREAD

**Issue by schneidmaster** [schneidmaster/gitreports.com#89]
Submitter: Huỳnh Quang Thái
Email: holdthehand@gmail.com
I've tried many times to clone my project from git by using git cloning command, everything is ok until it comes to step "Checking for connectivity", the git is stop working, so I don't know the reason why, but I've tried many times and try to reinstall other version of git, from the older version to the latest version, but it still not working on windows 10. 

Hope you fix the issue soon.

**Comment by Nightfirecat** [comment]
Sounds like a misunderstood submission -- this isn't the right place to report issues with Git.
